export default {
  header: {
    title: 'Header',
    registration: 'Sign up',
    login: 'Sign in',
  },
  main: {
    header: 'Boards',
    add: 'Add board',
    delete: 'Delete',
    edit: 'Edit',
    search: 'Search',
  },
  loginForm: {
    header: 'Sign in:',
  },
  registrationForm: {
    header: 'Sign up',
  },
  welcome: {
    header: 'Trello-clone helps teams move work forward.',
    main: `Collaborate, manage projects, and reach new productivity peaks. From high rises to the home office, the way your team works is unique—accomplish it all with Trello-clone.`,
    button: {
      registration: `Sign up-it's free!`,
    },
    about: {
      team: { name: 'Team', description: 'Something about team' },
      alice: 'some',
      dmitriy: 'some',
      timur: 'some',
    },
  },
  notFound: {
    header: '404: Page not found',
    goHome: 'Main page',
  },
  error: {
    text: 'Oops, something went wrong',
    button: 'Try again',
  },
  userForms: {
    login: 'Login',
    password: 'Password',
    passwordConfirmation: 'Password confirmation',
    email: 'E-mail',
    name: 'Name',
    isShort: '{{field}} is too short!',
    isLong: '{{field}} is too  long!',
    isRequired: '{{field}} is required',
    isInvalid: '{{field}} is invalid',
    passwordRequirements: 'Password can only contain Latin letters and numbers',
    matchPasswords: 'Passwords must match',
    reset: 'Reset',
    submit: 'Submit',
    delete: 'Delete user',
    enter: 'login',
    showPassword: 'Show password',
    unknownError: 'Unknown error. Please try later',
    invalidLoginOrPassword: 'Wrong login or password.',
    duplicateUser: 'User already exists!',
    userNotFound: 'User not found!',
    create: 'Create user',
    deleteConfirmation: 'Delete user "{{login}}"',
    logoutConfirmation: 'Logout user "{{login}}"',
  },
  userMenu: {
    logout: 'Logout',
    edit: 'Edit',
    delete: 'Delete user',
  },
  modal: {
    closeModal: 'Close modal dialog',
    confirmHeader: 'Confirm this action?',
    confirm: 'Confirm',
    deny: 'Deny',
  },
  column: {
    button: '+ Add another column',
    delete: 'Delete column',
    add: 'Add?',
  },
};
